'use client';
import {kitchenRequest,KitchenRequestError} from '@/lib/kitchen-client';
import {useEffect,useState,useRef} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Avatar,AvatarImage,AvatarFallback} from '@/components/ui/avatar';
import {Empty} from '@/components/ui/empty';
import {Switch} from '@/components/ui/switch';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Toaster,toast} from 'sonner';
import {ChefHat,ShoppingBag,Plus,Minus,UtensilsCrossed,Clock,Camera,Star,ReceiptText} from 'lucide-react';
const steps=['已下单','已接单','制作中','已完成','已取餐'];
const sample=[{id:'egg',name:'番茄炒蛋',description:'酸甜番茄裹着嫩鸡蛋，熟悉的家常味。',category:'素菜',available:1,image:'',allergens:'鸡蛋'},{id:'wings',name:'可乐鸡翅',description:'小火收汁，咸甜入味。每份 4 只。',category:'荤菜',available:1,image:'',allergens:'大豆、小麦'},{id:'rice',name:'蛋炒饭',description:'鸡蛋、葱花和米饭，热乎乎的一大碗。',category:'主食',available:1,image:'',allergens:'鸡蛋'},{id:'potato',name:'酸辣土豆丝',description:'爽脆酸辣，配米饭刚刚好。',category:'素菜',available:1,image:'',allergens:''}];
export default function Kitchen({signedIn,signIn,initialData,initialError=''}:{signedIn:boolean,signIn:string,initialData?:any,initialError?:string}){
const [data,setData]=useState<any>(initialData||{dishes:sample,orders:[],kitchenOrders:[],reviews:[],friends:[],profile:null,admin:false});const [loading,setLoading]=useState(false),[error,setError]=useState(initialError),[busy,setBusy]=useState(false),[cart,setCart]=useState<Record<string,number>>({}),[tab,setTab]=useState('menu'),[selected,setSelected]=useState<any>(null),[edit,setEdit]=useState<any>(null),[review,setReview]=useState<any>(null),[rating,setRating]=useState('5'),[comment,setComment]=useState(''),[name,setName]=useState(''),[room,setRoom]=useState(''),[note,setNote]=useState('');
const cursorRef=useRef<{created:string;id:string}|null>(null);const loadSequence=useRef(0);const orderRequest=useRef<{fingerprint:string;requestId:string}|null>(null);const placing=useRef(false);const [history,setHistory]=useState(false),[kitchenFilter,setKitchenFilter]=useState('active');
const [profileName,setProfileName]=useState(''),[profileRoom,setProfileRoom]=useState('');
function Person({name,avatar}:{name:string,avatar?:string}){return <span className="person"><Avatar><AvatarImage src={avatar||undefined} alt={name}/><AvatarFallback>{name.slice(0,1)||'?'}</AvatarFallback></Avatar><strong>{name}</strong></span>;}
useEffect(()=>{if(data.profile&&(data.profile.name||data.profile.room)){setProfileName(data.profile.name);setProfileRoom(data.profile.room);}},[data.profile?.name,data.profile?.room]);
async function load(){const sequence=++loadSequence.current;try{const d=await kitchenRequest(undefined,cursorRef.current?'?before='+encodeURIComponent(JSON.stringify(cursorRef.current)):'');if(sequence===loadSequence.current){setData(d);setError('');}return true;}catch(e:any){if(sequence===loadSequence.current)setError(e.message||'加载失败');return false;}finally{if(sequence===loadSequence.current)setLoading(false);}}
async function changeOrderPage(cursor:{created:string;id:string}|null){cursorRef.current=cursor;setHistory(!!cursor);setLoading(true);await load();}
useEffect(()=>{if(signedIn){const t=setInterval(()=>{if(document.visibilityState==='visible')load();},20000);return ()=>clearInterval(t);}},[signedIn]);
useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const controller=new AbortController();try{Promise.resolve(c.registerTool({name:'read_kitchen_menu',description:'查看当前菜单及可点状态',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(input&&Object.keys(input).length)throw new Error('不接受参数');return (await kitchenRequest()).dishes;}},{signal:controller.signal})).catch(()=>{});}catch{}return ()=>controller.abort();},[]);
const dishes=data.dishes;const entries=dishes.filter((d:any)=>cart[d.id]);const count=Object.values(cart).reduce((a,b)=>a+b,0);
useEffect(()=>{if(data.profile){setName(n=>n||data.profile.name);setRoom(r=>r||data.profile.room);}},[data.profile?.name,data.profile?.room]);
function add(d:any,delta=1){setCart(c=>({...c,[d.id]:Math.max(0,Math.min(20,(c[d.id]||0)+delta))}));}
async function send(body:any){setBusy(true);try{await kitchenRequest(body);const refreshed=await load();toast.success(refreshed?'已保存':'已保存，列表暂未刷新，请稍后重试刷新');return true;}catch(e:any){if(e instanceof KitchenRequestError&&e.status===409)await load();toast.error(e.message||'保存失败');return false;}finally{setBusy(false);}}
async function place(){if(placing.current)return;placing.current=true;try{const payload={action:'order',name,room,note,items:entries.map((d:any)=>({id:d.id,qty:cart[d.id]}))};const fingerprint=JSON.stringify(payload);if(orderRequest.current?.fingerprint!==fingerprint)orderRequest.current={fingerprint,requestId:crypto.randomUUID()};if(await send({...payload,requestId:orderRequest.current.requestId})){orderRequest.current=null;setCart({});setNote('');setTab('orders');if(cursorRef.current)await changeOrderPage(null);}}finally{placing.current=false;}}
async function upload(id:string,file?:File,target='order'){if(!file)return;setBusy(true);try{const f=new FormData();f.set('file',file);f.set('id',id);f.set('target',target);await kitchenRequest(f);await load();toast.success(target==='avatar'?'头像已更新':'照片已更新');}catch(e:any){toast.error(e.message);}finally{setBusy(false);}}
function Order({o,kitchen=false}:{o:any,kitchen?:boolean}){const items=JSON.parse(o.items);const hasReview=!!o.hasReview;return <article className="order"><div className="order-top"><div><small>#{o.id.slice(0,8).toUpperCase()} · {new Date(o.created).toLocaleString('zh-CN',{timeZone:'Europe/London',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small><h3>{kitchen?`${o.name} · ${o.room}`:'我的家常饭'}</h3></div><span className={'status s'+o.status}>{steps[o.status]}</span></div><div className="order-items">{items.map((i:any)=><p key={i.id}>{i.name} <span>× {i.qty}</span></p>)}</div>{o.note&&<p className="note">备注：{o.note}</p>}<div className="track">{steps.map((s,i)=><span key={s} className={i<=o.status?'done':''}>{s}</span>)}</div>{o.photo&&<img className="finished" src={o.photo} alt="这份订单的成品照片"/>}<div className="order-bottom"><div className="actions">{kitchen&&<label className="photo-button"><Camera size={16}/>成品照片<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(o.id,e.target.files?.[0])}/></label>}{o.status<4&&(kitchen||o.status===3)&&<button disabled={busy} onClick={()=>send({action:'status',id:o.id,status:o.status+1})}>{['接受订单','开始制作','完成出餐','确认取餐'][o.status]}</button>}{!kitchen&&o.status===4&&!hasReview&&<button onClick={()=>{setReview(o);setRating('5');setComment('');}}>写评价</button>}{hasReview&&<small>已评价</small>}</div></div></article>;}
return <><Toaster richColors position="top-center"/><header className="header"><a className="brand" href="/"><span className="brand-icon"><ChefHat/></span><span>Vita Kitchen<small>公寓小厨房</small></span></a></header><main><Tabs value={tab} onValueChange={setTab}><div className="nav-row"><TabsList className="nav-tabs" variant="line"><TabsTrigger value="menu"><UtensilsCrossed/>今日菜单</TabsTrigger><TabsTrigger value="orders"><ReceiptText/>我的订单</TabsTrigger><TabsTrigger value="reviews"><Star/>朋友评价</TabsTrigger><TabsTrigger value="friends">朋友 / 我的资料</TabsTrigger>{data.admin&&<TabsTrigger value="kitchen"><ChefHat/>厨房管理</TabsTrigger>}</TabsList></div>{error&&<div className="error" role="alert">{error}<div className="actions"><button onClick={load}>重试</button><a href={signIn} target="_top">重新登录</a></div></div>}{!signedIn&&<div className="sign-in">登录后就可以点菜、查看订单和评价。<a href={signIn} target="_top">使用 ChatGPT 登录</a></div>}
<TabsContent value="menu"><div className="menu-layout"><section><div className="page-heading"><div><h1>菜单</h1></div></div><div className="dish-grid">{dishes.map((d:any)=><article className={'dish '+(!d.available?'unavailable':'')} key={d.id}><button className={'dish-cover '+(!d.image?'typographic':'')} onClick={()=>setSelected(d)} aria-label={'查看'+d.name}>{d.image?<img src={d.image} alt={d.name}/>:<><span className="dish-art-name">{d.name}</span><UtensilsCrossed className="dish-symbol"/></>}<span className="dish-tag">{d.available?'今日可点':'今日休息'}</span></button><div className="dish-body"><button className="dish-name" onClick={()=>setSelected(d)}>{d.name}</button><div className="dish-bottom"><button className="add" disabled={!d.available||loading||!!error} onClick={()=>add(d)} aria-label={'添加'+d.name}><Plus size={20}/>{cart[d.id]>0&&<span>{cart[d.id]}</span>}</button></div></div></article>)}</div></section><aside className="cart" id="point-menu" tabIndex={-1}><div className="cart-title"><ShoppingBag/><h2>我的点菜单</h2><span>{count}</span></div>{entries.length===0?<div className="cart-empty"><UtensilsCrossed size={38}/><p>先选一道喜欢的菜</p><small>菜单里的 ＋ 会把它加进来</small></div>:<div className="cart-items">{entries.map((d:any)=><div className="cart-item" key={d.id}><div><strong>{d.name}</strong></div><div className="qty"><button aria-label={'减少'+d.name} onClick={()=>add(d,-1)}><Minus size={14}/></button><span>{cart[d.id]}</span><button aria-label={'增加'+d.name} onClick={()=>add(d)}><Plus size={14}/></button></div></div>)}</div>}<div className="cart-form"><label>怎么称呼你<input maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="你的昵称"/></label><label>房间号<input maxLength={20} value={room} onChange={e=>setRoom(e.target.value)} placeholder="例如 A305"/></label><label>口味备注<textarea maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder="少盐、不要葱……" rows={2}/></label>{signedIn?<button className="checkout" disabled={!count||!name.trim()||!room.trim()||busy||loading||!!error} onClick={place}>{busy?'正在提交…':'提交点菜'}</button>:<a className="checkout" target="_top" href={signIn}>登录后点菜</a>}</div></aside></div></TabsContent>
<TabsContent value="orders"><div className="section-heading order-heading"><h1>{history?'历史订单':'我的订单'}</h1><button className="secondary-button" disabled={loading} onClick={()=>{setLoading(true);load();}}>刷新</button></div>{loading?<p>正在加载订单…</p>:data.orders.length?<div className="orders">{data.orders.map((o:any)=><Order key={o.id} o={o}/>)}</div>:<Empty className="empty"><ShoppingBag/><h2>还没有订单</h2><p>选好菜后，订单会出现在这里。</p><button onClick={()=>setTab('menu')}>去看菜单</button></Empty>}<div className="order-pagination">{history&&<button className="secondary-button" disabled={loading} onClick={()=>changeOrderPage(null)}>返回最新订单</button>}{data.ordersNextCursor&&<button disabled={loading} onClick={()=>changeOrderPage(data.ordersNextCursor)}>更早的订单</button>}</div></TabsContent>
<TabsContent value="reviews"><div className="section-heading"><h1>朋友评价</h1></div>{data.reviews.length?<div className="review-grid">{data.reviews.map((r:any,i:number)=><article className="review" key={i}><span className="stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span><p>{r.comment}</p><div><Person name={r.name} avatar={r.avatar}/><small>{new Date(r.created).toLocaleDateString('zh-CN')}</small></div></article>)}</div>:<Empty className="empty"><Star/><h2>等第一位朋友的评价</h2><p>确认取餐后，就能在“我的订单”留下评分和感受。</p></Empty>}</TabsContent>
{data.admin&&<TabsContent value="kitchen"><div className="section-heading"><h1>厨房管理</h1></div><p className="kitchen-scope">显示全部待处理订单及最近 50 份已取餐订单。</p><div className="stats">{['等待接单','已接单','制作中','待取餐'].map((s,i)=><div key={s}><span>{s}</span><strong>{data.kitchenOrders.filter((o:any)=>o.status===i).length}</strong></div>)}</div><div className="kitchen-toolbar"><h2 className="subheading">订单管理</h2><div className="order-filters" aria-label="筛选厨房订单">{[['active','待处理'],['all','最近订单']].map(([value,label])=><button key={value} aria-pressed={kitchenFilter===value} className={kitchenFilter===value?'selected':''} onClick={()=>setKitchenFilter(value)}>{label}</button>)}</div></div>{data.kitchenOrders.some((o:any)=>kitchenFilter==='all'||o.status<4)?<div className="orders">{data.kitchenOrders.filter((o:any)=>kitchenFilter==='all'||o.status<4).map((o:any)=><Order key={o.id} o={o} kitchen/>)}</div>:<p className="empty-line">{kitchenFilter==='active'?'暂时没有待处理订单，可以歇一会儿。':'暂时没有订单，先准备今日菜单吧。'}</p>}<div className="manage-heading"><h2>菜单管理</h2><button onClick={()=>setEdit({name:'',description:'',category:'素菜',available:1,image:'',allergens:''})}><Plus size={16}/>添加菜品</button></div><div className="manage-list">{dishes.map((d:any)=><div key={d.id}><div className="manage-dish">{d.image&&<img src={d.image} alt={d.name}/>}<strong>{d.name}</strong></div><span>{d.available?'可点':'休息'}</span><label className="photo-button"><Camera size={16}/>{d.image?'换照片':'上传照片'}<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{upload(d.id,e.target.files?.[0],'dish');e.target.value='';}}/></label><button onClick={()=>setEdit({...d})}>编辑</button></div>)}</div></TabsContent>}
<TabsContent value="friends"><div className="section-heading"><h1>朋友 / 我的资料</h1></div><div className="friends-layout"><section className="profile-card"><h2>我的资料</h2>{signedIn?<><div className="avatar-editor"><Person name={profileName||'我'} avatar={data.profile?.avatar}/><label className="photo-button"><Camera size={16}/>{data.profile?.avatar?'换头像':'上传头像'}<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{upload('',e.target.files?.[0],'avatar');e.target.value='';}}/></label></div><label>名字 / 昵称<input maxLength={40} value={profileName} onChange={e=>setProfileName(e.target.value)}/></label><label>房间号（点餐时对厨房成员可见）<input maxLength={20} value={profileRoom} onChange={e=>setProfileRoom(e.target.value)}/></label><button disabled={busy||loading||!!error} onClick={async()=>{if(await send({action:'profile',name:profileName,room:profileRoom})){setName(profileName);setRoom(profileRoom);}}}>保存资料</button><small>保存名字后，会出现在下方朋友列表中。</small></>:<p>登录后可以设置名字和头像。</p>}</section><section className="friends-list"><h2>朋友们</h2>{data.friends?.length?<div className="friend-grid">{data.friends.map((f:any,i:number)=><div className="friend" key={i}><Person name={f.name} avatar={f.avatar}/></div>)}</div>:<Empty className="empty"><h3>还没有朋友资料</h3><p>加入网站后，每个人可以自己设置名字和头像。</p></Empty>}</section></div></TabsContent>
</Tabs>{tab==='menu'&&count>0&&<button className="mobile-cart-shortcut" onClick={()=>{const cart=document.getElementById('point-menu');cart?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});cart?.focus({preventScroll:true});}}><ShoppingBag size={20}/><span>已选 {count} 份</span><strong>查看点菜单</strong></button>}<footer><span>Vita Kitchen</span></footer></main>
<Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.description}</DialogDescription>{selected?.image&&<img className="detail-image" src={selected.image} alt={selected.name}/>}<p>含有的过敏原：{selected?.allergens||'未标注，请下单前向厨师确认'}</p><button disabled={!selected?.available||!!error||loading} onClick={()=>{add(selected);setSelected(null);}}>加入点菜单</button></DialogContent></Dialog>
<Dialog open={!!review} onOpenChange={v=>!v&&setReview(null)}><DialogContent><DialogTitle>这顿饭怎么样？</DialogTitle><DialogDescription>留下你的真实感受。</DialogDescription><Select value={rating} onValueChange={setRating}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[5,4,3,2,1].map(n=><SelectItem key={n} value={String(n)}>{'★'.repeat(n)} · {n} 星</SelectItem>)}</SelectContent></Select><textarea aria-label="评价内容" value={comment} onChange={e=>setComment(e.target.value)} maxLength={500} rows={4} placeholder="味道、分量，或者下次的小建议…"/><button disabled={busy} onClick={async()=>{if(await send({action:'review',id:review.id,rating:Number(rating),comment}))setReview(null);}}>提交评价</button></DialogContent></Dialog>
<Dialog open={!!edit} onOpenChange={v=>!v&&setEdit(null)}><DialogContent className="edit-dialog"><DialogTitle>{edit?.id?'修改菜品':'添加菜品'}</DialogTitle><DialogDescription>可以先只填菜名保存，再在菜单管理里上传照片。</DialogDescription>{edit&&<><label>菜名<input maxLength={50} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>简介<textarea maxLength={300} value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/></label><label>分类<Select value={edit.category} onValueChange={v=>setEdit({...edit,category:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['荤菜','素菜','主食'].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></label><label>过敏原<input maxLength={100} value={edit.allergens} onChange={e=>setEdit({...edit,allergens:e.target.value})}/></label><label className="switch-label">今天可点<Switch checked={!!edit.available} onCheckedChange={v=>setEdit({...edit,available:v?1:0})}/></label><button disabled={busy} onClick={async()=>{if(await send({action:'dish',dish:edit}))setEdit(null);}}>保存菜品</button></>}</DialogContent></Dialog></>;
}
