import {db,menu,identity,bucket,kitchenData,SignInRequired} from '@/lib/kitchen';
export const dynamic='force-dynamic';
const json=(data:any,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
const str=(v:any,max=300)=>typeof v==='string'&&v.trim().length<=max?v.trim():'';
export async function GET(){try{return json(await kitchenData());}catch(e){if(e instanceof SignInRequired)return json({error:'请重新登录。'},401);console.error(e);return json({error:'暂时无法加载，请稍后重试。'},503);}}
export async function POST(req:Request){try{const u=await identity();if(req.headers.get('origin')&&new URL(req.url).origin!==req.headers.get('origin'))return json({error:'无效请求'},403);if(req.headers.get('content-type')?.includes('multipart/form-data')){
const f=await req.formData();const file=f.get('file');const target=f.get('target')||'order';const id=str(f.get('id')||f.get('orderId'),100);
if(!['dish','order','avatar'].includes(String(target)))return json({error:'无效的上传目标'},400);
if(target!=='avatar'&&!u.admin)return json({error:'只有厨房管理员可以上传菜品照片'},403);
if(target==='dish'&&!await db().prepare('SELECT id FROM dishes WHERE id=?').bind(id).first())return json({error:'请先保存菜品，再上传照片'},404);
if(target==='order'&&!await db().prepare('SELECT id FROM orders WHERE id=?').bind(id).first())return json({error:'订单不存在'},404);
if(!(file instanceof File)||file.size===0||file.size>5*1024*1024)return json({error:'请选择小于 5MB 的 JPG、PNG 或 WebP 图片'},400);
const bytes=await file.arrayBuffer();const a=new Uint8Array(bytes);
const type=a.length>3&&a[0]===255&&a[1]===216&&a[2]===255?'image/jpeg':a.length>8&&[137,80,78,71,13,10,26,10].every((v,i)=>a[i]===v)?'image/png':a.length>12&&String.fromCharCode(...a.slice(0,4))==='RIFF'&&String.fromCharCode(...a.slice(8,12))==='WEBP'?'image/webp':null;
if(!type)return json({error:'请选择 JPG、PNG 或 WebP 图片；HEIC 图片请先转成 JPG'},400);
const key=crypto.randomUUID();const image='/api/images/'+key;await bucket().put(key,bytes,{httpMetadata:{contentType:type}});
try{if(target==='dish')await db().prepare('UPDATE dishes SET image=? WHERE id=?').bind(image,id).run();
else if(target==='order')await db().prepare('UPDATE orders SET photo=? WHERE id=?').bind(image,id).run();
else await db().prepare("INSERT INTO profiles (user,name,room,avatar) VALUES (?,'','',?) ON CONFLICT(user) DO UPDATE SET avatar=excluded.avatar").bind(u.userId,image).run();
}catch(e){await bucket().delete(key);throw e;}
return json({ok:true,image});}
const b:any=await req.json();
if(b.action==='profile'){const name=str(b.name,40),room=str(b.room,20);if(!name)return json({error:'请填写名字或昵称'},400);await db().prepare("INSERT INTO profiles (user,name,room,avatar) VALUES (?,?,?,'') ON CONFLICT(user) DO UPDATE SET name=excluded.name,room=excluded.room").bind(u.userId,name,room).run();return json({ok:true});}
if(b.action==='order'){const name=str(b.name,40),room=str(b.room,20),note=str(b.note,500);if(!name||!room||!Array.isArray(b.items)||b.items.length<1||b.items.length>30)return json({error:'请填写昵称、房间号并选择菜品'},400);const dishes:any[]=await menu() as any[];const ids=new Set();const items=[];let total=0;for(const x of b.items){const d=dishes.find(d=>d.id===x.id);if(!d||!d.available||!Number.isInteger(x.qty)||x.qty<1||x.qty>20||ids.has(x.id))return json({error:'菜品状态或数量已变化，请刷新菜单'},400);ids.add(x.id);items.push({id:d.id,name:d.name,qty:x.qty});}const id=crypto.randomUUID();await db().prepare('INSERT INTO orders (id,user,name,room,note,items,total,status,photo,created) VALUES (?,?,?,?,?,?,?,0,?,?)').bind(id,u.userId,name,room,note,JSON.stringify(items),total,'',new Date().toISOString()).run();return json({ok:true,id});}
if(b.action==='status'){const o:any=await db().prepare('SELECT * FROM orders WHERE id=?').bind(str(b.id,100)).first();if(!o)return json({error:'订单不存在'},404);if(!Number.isInteger(b.status)||b.status!==o.status+1||b.status>4)return json({error:'请按顺序更新订单状态'},400);if(!u.admin&&!(o.user===u.userId&&b.status===4))return json({error:'无权限'},403);await db().prepare('UPDATE orders SET status=? WHERE id=? AND status=?').bind(b.status,o.id,o.status).run();return json({ok:true});}
if(b.action==='review'){const o:any=await db().prepare('SELECT * FROM orders WHERE id=? AND user=?').bind(str(b.id,100),u.userId).first();if(!o||o.status!==4||!Number.isInteger(b.rating)||b.rating<1||b.rating>5)return json({error:'取餐后可以评价，评分为 1–5 星'},400);const comment=str(b.comment,500);if(!comment)return json({error:'请写一点用餐感受'},400);await db().prepare('INSERT INTO reviews (id,order_id,user,name,rating,comment,created) VALUES (?,?,?,?,?,?,?) ON CONFLICT(order_id) DO NOTHING').bind(crypto.randomUUID(),o.id,u.userId,o.name,b.rating,comment,new Date().toISOString()).run();return json({ok:true});}
if(b.action==='dish'){if(!u.admin)return json({error:'无权限'},403);const d=b.dish;if(!d||!str(d.name,50)||!str(d.category,20))return json({error:'请检查菜名和分类'},400);const image=str(d.image,500);if(image&&!/^\/(food\.jpg|api\/images\/[a-f0-9-]+)$/.test(image))return json({error:'图片地址无效'},400);await db().prepare('INSERT INTO dishes (id,name,description,category,price,available,image,allergens) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,category=excluded.category,price=excluded.price,available=excluded.available,image=excluded.image,allergens=excluded.allergens').bind(str(d.id,100)||crypto.randomUUID(),str(d.name,50),str(d.description,300),str(d.category,20),0,d.available?1:0,image,str(d.allergens,100)).run();return json({ok:true});}return json({error:'无效操作'},400);
}catch(e){if(e instanceof SignInRequired)return json({error:'请重新登录。'},401);console.error(e);return json({error:'保存失败，请稍后再试。你的输入仍然保留。'},503);}}
